### ISSUE TITLE
hapi-alive used?

### ISSUE THREAD

**Issue by jupl** [Boulangerie/hapiour-decorators#5]
I noticed that `hapi-alive` is listed as a dependency, but it is not being used in the main codebase. If so it appears to be an unneeded dependency being pulled in for `hapiour-decorators` when installing from NPM. Perhaps it needs to be removed or moved to `devDependencies`?

**Comment by heiso** [comment]
You'r right, this dependency is only used by the integration test.
Fixed by https://github.com/Boulangerie/hapiour-decorators/pull/6
Thx @jupl
