### ISSUE TITLE
Support dependency injection container

### ISSUE THREAD

**Issue by patrickmichalina** [Boulangerie/hapiour-decorators#9]
Offer a new bootstrap method that boostraps the app with a container to support a simple injector model. Mainly to work with [typedi](https://github.com/pleerock/typedi) project.

**Comment by patrickmichalina** [comment]
I am ready to submit a PR today, but wondering if you would even want this feature, otherwise I will fork! Thanks.

**Comment by heiso** [comment]
Good idea, will have a look to your PR ASAP.
We just have to figure out a way to support other dependencies injection lib :/

**Comment by patrickmichalina** [comment]
Thanks!

I assume most DI libs will have a .get() method of somekind, otherwise we could have an overload that allows a function to be passed in that handles the get/return of the service from the container

**Comment by heiso** [comment]
Yep, could be a solution. I'm currently testing your PR to add this feature on hapiour soon :)

**Comment by heiso** [comment]
It's alive !
https://github.com/Boulangerie/hapiour-decorators/pull/12

bump your dependency to 1.4.0

**Comment by patrickmichalina** [comment]
Thanks!
